### PR TITLE
Fixed Carthage build error.

### PR DESCRIPTION
**Pull request by JFKingsley**
A recent change in syntax appears to have removed a method that was previously working. 

As such, i've added an alternative implementation to maintain cross-platform compatibility and the build appears to be working fine now.

Thanks!

### CODE REVIEW

**Comment by mamaral** [comment]
Looks good - thank you very much!

**Comment by JFKingsley** [comment]
You're welcome! Thanks for building such a great library.

**Comment by mamaral** [comment]
@JFKingsley Are you using it in any productions apps? I'd love to see what people are using it for.

**Comment by JFKingsley** [comment]
Yeah, i'm actually using it in two production projects right now, and it's been working a treat! I'll throw links over on release if you want some examples.

(Unrelated, but i've just checked the install and since the latest git tag is still 0.0.3, it's installing the old, broken version. Mind bumping it?)

**Comment by mamaral** [comment]
yeah ill take care of that now - I'd love links!

**Comment by mamaral** [comment]
Pushed v0.1.0 to cocoa pods trunk - should be all set!

**Comment by JFKingsley** [comment]
Yep, looks like that's all working!

I'll be sure to drop some links when everything's up.

**Pull request merged**
