### PR TITLE
Carthage Support / OSX Support merge

### PR DESCRIPTION
**Pull request by remaerd**
Hello, Thanks for your framework.

I make many changes to make it support Carthage and OSX. I moved Folders and Files here and there, Make two new targets in the Xcode Project. Mark many internal methods as public. So now Neon supports Carthage and OSX. (I'm not using Cocoapods and I make some big changes in this branch. So I haven't change the Podspec because I can't)

Please take a look at this commit and tell me what you think. Thank you.

### CODE REVIEW

**Comment by mamaral** [comment]
Looks great so far - I've cloned your branch and am testing it on my end. Thanks! I'll let you know.

**Comment by schickling** [comment]
Has something changed about this? Getting:
```
A shell task failed with exit code 66:
xcodebuild: error: Scheme NeonMacDemo is not currently configured for the build action.
```

**Comment by mamaral** [comment]
Potentially, I had to work some project changes in order to get unit testing / code coverage setup, and I'm not an expert on Carthage integration, so I'd probably want some help on that if there's now a problem.

**Comment by schickling** [comment]
@remaerd could you maybe look into this again? I couldn't really figure out whats wrong...

**Comment by remaerd** [comment]
@schickling When a target is marked as 'Shared'. Carthage will try to build it as a framework. Someone made changes in the Xcode project. It should only mark the iOS / OSX Dynamic framework as 'Shared'. If you try to build the 'Scheme NeonMacDemo' with Carthage. It's will definitely fail to build the framework.

I'm no longer using Neon and I'm not familiar with the changes i missed. You should fork Neon and make those changes.

Cheers.

**Comment by schickling** [comment]
Out of curiosity: Why don't you use Neon anymore. What are you using now?

**Comment by remaerd** [comment]
@schickling I need to use Native APIs such as UIStackView / NSStackView and NSLayoutConstraint in my app. Since Neon is not base on both of them and it not production ready, I need to use the Apple Standard APIs to create my app.

**Pull request merged**
